# Generated by Django 2.2.4 on 2019-08-29 05:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190829_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 5, 20, 13, 82026, tzinfo=utc)),
        ),
    ]
