# Generated by Django 2.2.4 on 2019-08-29 05:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190829_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 17, 22, 43, 472642, tzinfo=utc)),
        ),
    ]
